<?php

/**
 * @file
 * Field formatter to expand and collapse text of a field.
 */

/**
 * Implement hook_field_formatter_info().
 */
function jquery_expander_field_formatter_info() {
  return array(
    'jquery_expander' => array(
      'label' => t('Expander'),
      'field types' => array('text', 'text_long', 'text_with_summary'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function jquery_expander_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  static $delta = array();

  foreach ($items as $delta => $item) {
    $output = _text_sanitize($instance, $langcode, $item, 'value');
    $element[$delta] = array(
      '#markup' => $output,
      '#prefix' => '<div class="field-expander-' . $delta . '">',
      '#suffix' => '</div>'
    );
    $element[$delta]['#attached']['js'] = array(
      array(drupal_get_path('module', 'jquery_expander') . '/jquery_expander.js'),
      array(libraries_get_path('expander') . '/jquery.expander.js'),
      array('data' => array('jqueryExpander' => array($delta => array())), 'type' => 'setting'),
    );
    ++$delta;
  }

  return $element;
}